export const ALL_USERS = 'ALL_USERS';
export const GET_USER = 'GET_USER';
export const EDIT_USER = 'EDIT_USER';
export const DELETE_USER = 'DELETE_USER';
export const PROCESS_LOADING = 'PROCESS_LOADING';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const SET_USER_ROLES = 'USER_ROLES';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// export const SET_CD_HEADER_FOR_RECEIPT = 'SET_CD_HEADER_FOR_RECEIPT';
// export const SET_CD_HEADER_FOR_DEPOSIT = 'SET_CD_HEADER_FOR_DEPOSIT';
// export const SET_CD_HEADER_FOR_CLEARING = 'CLEAR_ERRORS';
// export const SET_CD_HEADER_CLEARED = 'SET_CD_HEADER_FOR_CLEARING';
// export const SET_CD_HEADER_CANCELLED = 'SET_CD_HEADER_CANCELLED';
// export const SET_CD_HEADER_BOUNCED = 'SET_CD_HEADER_BOUNCED';

export const SET_CD_HEADER_SORT = 'SET_CD_HEADER_SORT';

